/* Мінімальний service worker AI Ebook Reader.
 * Єдина мета — щоб застосунок встановлювався як PWA і відкривав свою "оболонку"
 * (HTML/CSS/JS-бібліотеки, іконки) навіть без мережі. Нічого динамічного тут не
 * кешується: жодних AI-запитів, жодного тексту книги, жодних ключів.
 *
 * Правило безпеки: кешуємо ЛИШЕ GET-запити ДО ВЛАСНОГО ПОХОДЖЕННЯ (свій сайт).
 * Усе інше — запити до generativelanguage.googleapis.com (Gemini), api.groq.com
 * (Groq), translate.googleapis.com (переклад), будь-які POST — завжди йде напряму
 * в мережу в обхід service worker'а й ніколи не потрапляє в кеш. API-ключі
 * зберігаються лише в localStorage сторінки, який service worker узагалі не бачить.
 */
'use strict';

// Content identity generated by tools/version_app_shell.py from the versioned HTML.
// The installed HTML and script set form one offline snapshot.
const CACHE_NAME = 'ai-reader-shell-5ebeab50a6ec';

// Скільки чекати на мережу для НАВІГАЦІЇ (сама сторінка), перш ніж показати
// закешовану версію. Досить коротко, щоб застосунок відчувався швидким навіть на
// поганому зв'язку, і досить довго, щоб не відкидати мережу заради кешу вже за
// секунду. Це і є той запобіжник, що не дає встановленому PWA надовго застрягти
// на старій (потенційно вразливій) версії index.html.
const NAVIGATION_TIMEOUT_MS = 3500;

const APP_SHELL = [
    './',
    './index.html',
    './manifest.webmanifest',
    './icons/icon-192.png',
    './icons/icon-512.png',
    './js/core.js?v=02b138b56fe0',
    './js/lang-detect.js?v=21625d365df7',
    './js/ai-client.js?v=0fc54c25e41f',
    './js/selection.js?v=887b5c4cb5a3',
    './js/learning-stats.js?v=67246f255f39',
    './js/pdf-render.js?v=64ef9f00575d',
    './js/tts.js?v=64539ee7a830',
    './js/translation.js?v=3a8c557ecf71',
    './js/grammar-svo.js?v=d6c923f45e21',
    './js/navigation.js?v=cd49774de655',
    './js/formats.js?v=590fbe43ebc9',
    './js/pdf-zoom-pan.js?v=998e78d2c132',
    './js/pdf-ink.js?v=7ab822ef42a8',
    './js/pdf-crop.js?v=93672612bda6',
    './js/dictation.js?v=cd46e7d595c8',
    './js/ui-tooltip.js?v=1985b4724fd6',
    './js/onboarding.js?v=30c9f576755e',
    './js/quick-wheel.js?v=3ccf1bbd4ddc',
    './js/main.js?v=a6e5adcc808c',
    './js/pwa-lifecycle.js?v=6f08199a60e4',
    './archive-guard.worker.js',
    './vendor/jszip-3.10.1.min.js',
    './vendor/mammoth-1.6.0.browser.min.js',
    './vendor/marked-18.0.12.umd.js',
    './vendor/pdf-6.3.289.min.mjs',
    './vendor/pdf-6.3.289.worker.min.mjs',
    // PDF.js falls back to its own bundled pure-JS decoders (already covered by
    // the worker script above) when these WASM assets can't be fetched, so a
    // scanned/JPEG2000/JBIG2 PDF still renders correctly offline without them —
    // confirmed directly. But leaving them uncached means EVERY offline PDF
    // open wastes time on a network request that's guaranteed to fail before
    // falling back to the slower JS path. Precaching them keeps the fast WASM
    // path available offline too.
    './vendor/pdfjs-6.3.289/wasm/openjpeg.wasm',
    './vendor/pdfjs-6.3.289/wasm/openjpeg_nowasm_fallback.js',
    './vendor/pdfjs-6.3.289/wasm/jbig2.wasm',
    './vendor/pdfjs-6.3.289/wasm/jbig2_nowasm_fallback.js',
    './vendor/pdfjs-6.3.289/wasm/qcms_bg.wasm'
];

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => cache.addAll(APP_SHELL))
            .then(() => self.skipWaiting())
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((names) => Promise.all(
                names.filter((name) => name.startsWith('ai-reader-shell-') && name !== CACHE_NAME).map((name) => caches.delete(name))
            ))
            .then(() => self.clients.claim())
    );
});

// Chrome MUST NOT be handed a Response whose own `redirected` flag is true
// for a navigation FetchEvent — it silently fails the ENTIRE navigation with
// net::ERR_FAILED instead of displaying it (undocumented in MDN, but real and
// reproducible: this is exactly how the installed PWA shortcut broke —
// Cloudflare Pages 308-redirects /index.html -> /, so both a live fetch()
// of that URL and the copy `cache.addAll()` stored for it carry
// `redirected:true` forever, and every future navigation to that exact URL
// — including the shortcut's own start_url — hit this wall, online or off).
// Reconstructing a plain Response with the same body/status/headers has no
// redirect history and is always safe to hand to respondWith(); this heals
// it for ANY navigation URL, not just the one that prompted the fix, so an
// already-installed shortcut still pointed at the old /index.html start_url
// self-heals the moment this worker updates — no reinstall required.
async function stripRedirectHistory(res) {
    if (!res || !res.redirected) return res;
    return new Response(await res.clone().blob(), { status: res.status, statusText: res.statusText, headers: res.headers });
}

// Навігація (сам HTML-документ, включно зі стартом standalone-PWA) — мережа-спочатку
// з коротким таймаутом: онлайн-користувач завжди отримує code з сервера (а не вчорашню
// версію з кешу), офлайн чи повільна мережа — останню робочу закешовану. Саме тут жив
// ризик, що встановлений на планшеті PWA місяцями працює зі старою версією index.html.
async function networkFirstForNavigation(req) {
    const networkPromise = fetch(req).then((res) => {
        // Keep the installed offline HTML paired with its precached script versions.
        // A network navigation must not replace only one half of that snapshot.
        return res;
    }).catch(() => null);

    const timedOut = await Promise.race([
        networkPromise.then(() => false),
        new Promise((resolve) => setTimeout(() => resolve(true), NAVIGATION_TIMEOUT_MS))
    ]);

    if (!timedOut) {
        const res = await networkPromise;
        if (res && res.ok) return stripRedirectHistory(res);
    }

    // Мережа не встигла вчасно, впала або відповіла помилкою — власний кеш, а якщо
    // саме цього шляху там ще нема, фолбек на закешований index.html (той самий "app
    // shell" для будь-якої навігації). Only installing a complete new shell updates
    // the offline snapshot; online navigation still receives the network response.
    const cache = await caches.open(CACHE_NAME);
    const cached = (await cache.match(req)) || (await cache.match('./index.html')) || (await cache.match('./'));
    if (cached) return stripRedirectHistory(cached);
    const late = await networkPromise;
    if (late && late.ok) return stripRedirectHistory(late);
    return new Response('Offline', { status: 503, statusText: 'Offline' });
}

self.addEventListener('fetch', (event) => {
    const req = event.request;

    // Ніколи не чіпаємо нічого, крім звичайного GET, і ніколи — чужі домени.
    // Це і є той бар'єр, що не дає в кеш потрапити запитам до AI/перекладу чи
    // будь-чому, що несе API-ключ чи відповідь моделі.
    if (req.method !== 'GET') return;
    const url = new URL(req.url);
    if (url.origin !== self.location.origin) return;

    if (req.mode === 'navigate') {
        event.respondWith(networkFirstForNavigation(req));
        return;
    }

    // Only the declared shell is cacheable; API requests and arbitrary same-origin
    // resources never enter this cache. Query versions prevent old JS/new HTML mixes.
    const shellUrls = APP_SHELL.map(path => new URL(path, self.location.href).href);
    if (!shellUrls.includes(url.href)) return;
    event.respondWith(caches.open(CACHE_NAME).then(async cache => {
        const cached = await cache.match(req);
        return cached || fetch(req);
    }));
});
