/* Мінімальний service worker AI Ebook Reader.
 * Єдина мета — щоб застосунок встановлювався як PWA і відкривав свою "оболонку"
 * (HTML/CSS/JS-бібліотеки, іконки) навіть без мережі. Нічого динамічного тут не
 * кешується: жодних AI-запитів, жодного тексту книги, жодних ключів.
 *
 * Правило безпеки: кешуємо ЛИШЕ GET-запити ДО ВЛАСНОГО ПОХОДЖЕННЯ (свій сайт).
 * Усе інше — запити до generativelanguage.googleapis.com (Gemini), api.groq.com
 * (Groq), translate.googleapis.com (переклад), будь-які POST — завжди йде напряму
 * в мережу в обхід service worker'а й ніколи не потрапляє в кеш. API-ключі
 * зберігаються лише в localStorage сторінки, який service worker узагалі не бачить.
 */
'use strict';

// Content identity generated by tools/version_app_shell.py from the versioned HTML.
// The installed HTML and script set form one offline snapshot.
const CACHE_NAME = 'ai-reader-shell-3b64de0d1d0a';

// Скільки чекати на мережу для НАВІГАЦІЇ (сама сторінка), перш ніж показати
// закешовану версію. Досить коротко, щоб застосунок відчувався швидким навіть на
// поганому зв'язку, і досить довго, щоб не відкидати мережу заради кешу вже за
// секунду. Це і є той запобіжник, що не дає встановленому PWA надовго застрягти
// на старій (потенційно вразливій) версії index.html.
const NAVIGATION_TIMEOUT_MS = 3500;

const APP_SHELL = [
    './',
    './index.html',
    './manifest.webmanifest',
    './icons/icon-192.png',
    './icons/icon-512.png',
    './js/core.js?v=9c5a32634c1a',
    './js/lang-detect.js?v=025a440febe3',
    './js/ai-client.js?v=a7a5f853ab94',
    './js/selection.js?v=673c404a303c',
    './js/pdf-render.js?v=7d5c650a8f84',
    './js/tts.js?v=acafd96cc392',
    './js/translation.js?v=f5a89ff9d11a',
    './js/grammar-svo.js?v=77ced879bc70',
    './js/navigation.js?v=85973c0a546d',
    './js/formats.js?v=7fdd67290f8e',
    './js/pdf-zoom-pan.js?v=998e78d2c132',
    './js/pdf-ink.js?v=ad208a2b29f2',
    './js/pdf-crop.js?v=93672612bda6',
    './js/dictation.js?v=cd46e7d595c8',
    './js/ui-tooltip.js?v=24fafda1df3c',
    './js/onboarding.js?v=30c9f576755e',
    './js/main.js?v=6efddd5a8ba7',
    './js/pwa-lifecycle.js?v=b9824003afbb',
    './archive-guard.worker.js',
    './vendor/jszip-3.10.1.min.js',
    './vendor/mammoth-1.6.0.browser.min.js',
    './vendor/pdf-6.3.289.min.mjs',
    './vendor/pdf-6.3.289.worker.min.mjs'
];

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => cache.addAll(APP_SHELL))
            .then(() => self.skipWaiting())
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((names) => Promise.all(
                names.filter((name) => name.startsWith('ai-reader-shell-') && name !== CACHE_NAME).map((name) => caches.delete(name))
            ))
            .then(() => self.clients.claim())
    );
});

// Навігація (сам HTML-документ, включно зі стартом standalone-PWA) — мережа-спочатку
// з коротким таймаутом: онлайн-користувач завжди отримує code з сервера (а не вчорашню
// версію з кешу), офлайн чи повільна мережа — останню робочу закешовану. Саме тут жив
// ризик, що встановлений на планшеті PWA місяцями працює зі старою версією index.html.
async function networkFirstForNavigation(req) {
    const networkPromise = fetch(req).then((res) => {
        // Keep the installed offline HTML paired with its precached script versions.
        // A network navigation must not replace only one half of that snapshot.
        return res;
    }).catch(() => null);

    const timedOut = await Promise.race([
        networkPromise.then(() => false),
        new Promise((resolve) => setTimeout(() => resolve(true), NAVIGATION_TIMEOUT_MS))
    ]);

    if (!timedOut) {
        const res = await networkPromise;
        if (res && res.ok) return res;
    }

    // Мережа не встигла вчасно, впала або відповіла помилкою — власний кеш, а якщо
    // саме цього шляху там ще нема, фолбек на закешований index.html (той самий "app
    // shell" для будь-якої навігації). Only installing a complete new shell updates
    // the offline snapshot; online navigation still receives the network response.
    const cache = await caches.open(CACHE_NAME);
    const cached = (await cache.match(req)) || (await cache.match('./index.html')) || (await cache.match('./'));
    if (cached) return cached;
    const late = await networkPromise;
    return late || new Response('Offline', { status: 503, statusText: 'Offline' });
}

self.addEventListener('fetch', (event) => {
    const req = event.request;

    // Ніколи не чіпаємо нічого, крім звичайного GET, і ніколи — чужі домени.
    // Це і є той бар'єр, що не дає в кеш потрапити запитам до AI/перекладу чи
    // будь-чому, що несе API-ключ чи відповідь моделі.
    if (req.method !== 'GET') return;
    const url = new URL(req.url);
    if (url.origin !== self.location.origin) return;

    if (req.mode === 'navigate') {
        event.respondWith(networkFirstForNavigation(req));
        return;
    }

    // Only the declared shell is cacheable; API requests and arbitrary same-origin
    // resources never enter this cache. Query versions prevent old JS/new HTML mixes.
    const shellUrls = APP_SHELL.map(path => new URL(path, self.location.href).href);
    if (!shellUrls.includes(url.href)) return;
    event.respondWith(caches.open(CACHE_NAME).then(async cache => {
        const cached = await cache.match(req);
        return cached || fetch(req);
    }));
});
